version: '3'

services:
  minetest-poc:
    build:
      context: .
      dockerfile: Dockerfile.minetest
    image: metacoma/mine9wm:latest
#    depends_on:
#      - jsonfs
#      - kubernetes
#      - sshfs-ob0
#      - sshfs-ob1
#      - sshfs-ob2
    privileged: true
    networks:
      - minetest-poc
    ports:
      - 0.0.0.0:30000:30000/udp 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./games/mine9wm:/usr/local/games/mine9wm
      - ./files/minetest.conf:/usr/local/etc/minetest.conf  
    user: root
#        mount -t 9p -o tcp,name=`whoami`,uname=`whoami`,port=5640 jsonfs /tmp/json
    entrypoint: 
      - sh
      - -exc
      - |
        test -d /9gridchan || mkdir /9gridchan 
        test -d /inferno || mkdir /inferno
        9pfs -p 6666 192.168.1.133 /9gridchan
        9pfs -p 3333 192.168.1.253 /inferno
        /usr/local/bin/minetestserver --config /usr/local/etc/minetest.conf --gameid mine9wm 

  inferno: 
    build:
      context: .
      dockerfile: Dockerfile.inferno
    image: metacoma/inferno-os
    volumes:
      - ./files/inferno/:/usr/inferno/host:ro
      - ./files/inferno/profile:/usr/inferno/lib/sh/profile:ro
    ports:
      - 0.0.0.0:1025:1025
    networks:
      - minetest-poc
    entrypoint:  
      - sh
      - -exc
      - |
        emu /dis/sh /lib/sh/profile

  inferno-client: 
    build:
      context: .
      dockerfile: Dockerfile.inferno
    image: metacoma/inferno-os
    volumes:
      - ./files/inferno/:/usr/inferno/host:ro
    networks:
      - minetest-poc
    entrypoint:  
      - sh
      - -exc
      - |
        sleep 360000000
      
networks:
  minetest-poc:
