version: '3'

services:
  minetest-poc:
    build:
      context: .
      dockerfile: Dockerfile.minetest
    image: minetest/mine9wm:latest
    depends_on:
      - jsonfs
    privileged: true
    networks:
      - minetest-poc
    ports:
      - 0.0.0.0:30000:30000/udp 
    volumes:
      - ./games/mine9wm:/usr/local/games/mine9wm
      - ./files/minetest.conf:/usr/local/etc/minetest.conf  
    user: root
#        mount -t 9p -o tcp,name=`whoami`,uname=`whoami`,port=5640 jsonfs /tmp/json
    entrypoint: 
      - sh
      - -exc
      - |
        test -d /tmp/json || mkdir /tmp/json
        9mount '!tcp!jsonfs!5640' /tmp/json/
        /usr/local/bin/minetestserver --config /usr/local/etc/minetest.conf --gameid mine9wm 

#        /usr/local/bin/minetestserver --config /usr/local/etc/minetest.conf --gameid mine9wm  --trace --verbose
      
  jsonfs: 
    build:
      context: 9p/jsonfs
    image: metacoma/9p-jsonfs:latest
    networks:
      - minetest-poc
    volumes:
      - ./files/json/example.json:/tmp/json
    entrypoint: 
      - sh 
      - -c
      - |
        ./jsonfs -D -v -a :5640 /tmp/json

networks:
  minetest-poc:
