FROM i386/ubuntu:bionic AS builder
#FROM i386/alpine:latest


WORKDIR /usr

RUN apt update && apt-get install -y git build-essential


WORKDIR /usr/

ENV INFERNO_BRANCH=master
ENV INFERNO_COMMIT=ed97654bd7a11d480b44505c8300d06b42e5fefe
  

RUN git clone --depth 1 -b ${INFERNO_BRANCH} https://bitbucket.org/inferno-os/inferno-os 

WORKDIR /usr/inferno-os


ENV PATH=$PATH:/usr/inferno-os/Linux/386/bin

# RUN apk add --update libc6-compat
#RUN apk add --update libc6-compat

RUN \
  export PATH=$PATH:/usr/inferno-os/Linux/386/bin                             \
  export MKFLAGS='SYSHOST=Linux OBJTYPE=386 CONF=emu-g ROOT='/usr/inferno-os; \
  git reset --hard ${INFERNO_COMMIT}            && \
  /usr/inferno-os/Linux/386/bin/mk $MKFLAGS mkdirs                            && \
  /usr/inferno-os/Linux/386/bin/mk $MKFLAGS emuinstall                        && \
  /usr/inferno-os/Linux/386/bin/mk $MKFLAGS emunuke

FROM i386/ubuntu:bionic
ENV ROOT_DIR /usr/local/inferno

COPY --from=builder /usr/inferno-os/Linux/386/bin/emu-g /usr/bin
COPY --from=builder /usr/inferno-os/dis $ROOT_DIR/root
COPY --from=builder /usr/inferno-os/appl $ROOT_DIR/root
COPY --from=builder /usr/inferno-os/lib $ROOT_DIR/root
COPY --from=builder /usr/inferno-os/module $ROOT_DIR/root
COPY --from=builder /usr/inferno-os/usr $ROOT_DIR/root


ENTRYPOINT ["emu-g"]
