version: '3'

services:
  minetest-poc:
    build:
      context: .
      dockerfile: Dockerfile.minetest
    image: metacoma/mine9wm:latest
    depends_on:
      - jsonfs
      - kubernetes
    privileged: true
    networks:
      - minetest-poc
    ports:
      - 0.0.0.0:30000:30000/udp 
    volumes:
      - ./games/mine9wm:/usr/local/games/mine9wm
      - ./files/minetest.conf:/usr/local/etc/minetest.conf  
    user: root
#        mount -t 9p -o tcp,name=`whoami`,uname=`whoami`,port=5640 jsonfs /tmp/json
    entrypoint: 
      - sh
      - -exc
      - |
        test -d /kubernetes || mkdir /kubernetes
        9mount '!tcp!kubernetes!1800' /kubernetes
        /usr/local/bin/minetestserver --config /usr/local/etc/minetest.conf --gameid mine9wm 

#        9mount '!tcp!jsonfs!5640' /tmp/json/
#        /usr/local/bin/minetestserver --config /usr/local/etc/minetest.conf --gameid mine9wm  --trace --verbose

  kubernetes:
    build:
      context: .
      dockerfile: Dockerfile.inferno
    image: metacoma/inferno-os
    privileged: true
    expose:
      - 1800
    cap_add:
      - SYS_ADMIN
    networks:
      - minetest-poc
    volumes:
      - ./token:/root/.kube/token
      - ./kubeconfig:/root/.kube/config
      - /dev/fuse:/dev/fuse
      - ~/.aws/:/root/.aws
      - ./files/inferno/:/usr/inferno/host
    entrypoint:
      - sh 
      - -exc
      - |
        test -d /usr/inferno/kubernetes || mkdir /usr/inferno/kubernetes
        kubefuse -v /usr/inferno/kubernetes &
        emu /dis/sh /host/export.sh
      
      
           
    
      
  jsonfs: 
    build:
      context: 9p/jsonfs
    image: metacoma/9p-jsonfs:latest
    networks:
      - minetest-poc
    volumes:
      - ./files/json/example.json:/tmp/json
    entrypoint: 
      - sh 
      - -c
      - |
        ./jsonfs -D -v -a :5640 /tmp/json

networks:
  minetest-poc:
