version: '3'

services:
  minetest-poc:
    build:
      context: .
      dockerfile: Dockerfile.minetest
    image: metacoma/mine9wm:latest
    depends_on:
      - jsonfs
#      - kubernetes
      - sshfs-ob0
      - sshfs-ob1
      - sshfs-ob2
    privileged: true
    networks:
      - minetest-poc
    ports:
      - 0.0.0.0:30000:30000/udp 
    volumes:
      - ./games/mine9wm:/usr/local/games/mine9wm
      - ./files/minetest.conf:/usr/local/etc/minetest.conf  
    user: root
#        mount -t 9p -o tcp,name=`whoami`,uname=`whoami`,port=5640 jsonfs /tmp/json
    entrypoint: 
      - sh
      - -exc
      - |
        test -d /kubernetes || mkdir /kubernetes 
        test -d /ob0 || mkdir /ob0
        test -d /ob1 || mkdir /ob1
        test -d /ob2 || mkdir /ob2
        test -d /gridchan || mkdir /gridchan 
        9pfs -p 6666 192.168.1.160 /gridchan
        sleep 3
        /usr/local/bin/minetestserver --config /usr/local/etc/minetest.conf --gameid mine9wm 

#        9mount '!tcp!sshfs-ob0!1800' /ob0
#        9mount '!tcp!sshfs-ob1!1800' /ob1
#        9mount '!tcp!sshfs-ob2!1800' /ob2
#        9mount '!tcp!kubernetes!1800' /kubernetes

#        9mount '!tcp!jsonfs!5640' /tmp/json/
#        /usr/local/bin/minetestserver --config /usr/local/etc/minetest.conf --gameid mine9wm  --trace --verbose

  inferno: 
    build:
      context: .
      dockerfile: Dockerfile.inferno
    image: metacoma/inferno-os
    networks:
      - minetest-poc
    entrypoint:  
      - sh
      - -exc
      - |
        /bin/sleep 36000
        
    

  kubernetes:
    build:
      context: .
      dockerfile: Dockerfile.inferno
    image: metacoma/inferno-os
    privileged: true
    expose:
      - 1800
    cap_add:
      - SYS_ADMIN
    networks:
      - minetest-poc
    volumes:
      - ./token:/root/.kube/token
      - ./kubeconfig:/root/.kube/config
      - /dev/fuse:/dev/fuse
      - ~/.aws/:/root/.aws
      - ./files/inferno/:/usr/inferno/host:ro
    environment:
      - MOUNT_POINT=/usr/inferno/kubernetes
      - STYX_PORT=1800
    entrypoint:
      - sh 
      - -exc
      - |
        test -d $${MOUNT_POINT} || mkdir $${MOUNT_POINT}
        kubefuse -v $${MOUNT_POINT} &
        emu /dis/sh /host/export.sh /`basename $${MOUNT_POINT}` $${STYX_PORT}

  sshfs-ob0:
    build:
      context: .
      dockerfile: Dockerfile.sshfs
    image: metacoma/inferno-os-sshfs:latest
    privileged: true
    expose:
      - 1800
    cap_add:
      - SYS_ADMIN
    networks:
      - minetest-poc
    volumes:
      - ~/.ssh:/root/.ssh
      - ./files/inferno/:/usr/inferno/host:ro
    environment:
      - MOUNT_POINT=/usr/inferno/ob0
      - SSH_HOST=ob0
      - STYX_PORT=1800
    entrypoint:
      - sh 
      - -exc
      - |
        chown -R root:root /root/.ssh
        test -d $${MOUNT_POINT} || mkdir $${MOUNT_POINT}
        sshfs $${SSH_HOST}:/ $${MOUNT_POINT}
        emu /dis/sh /host/export.sh /`basename $${MOUNT_POINT}` $${STYX_PORT}

  sshfs-ob1:
    build:
      context: .
      dockerfile: Dockerfile.sshfs
    image: metacoma/inferno-os-sshfs:latest
    privileged: true
    expose:
      - 1800
    cap_add:
      - SYS_ADMIN
    networks:
      - minetest-poc
    volumes:
      - ~/.ssh:/root/.ssh
      - ./files/inferno/:/usr/inferno/host:ro
    environment:
      - MOUNT_POINT=/usr/inferno/ob1
      - SSH_HOST=ob1
      - STYX_PORT=1800
    entrypoint:
      - sh 
      - -exc
      - |
        chown -R root:root /root/.ssh
        test -d $${MOUNT_POINT} || mkdir $${MOUNT_POINT}
        sshfs $${SSH_HOST}:/ $${MOUNT_POINT}
        emu /dis/sh /host/export.sh /`basename $${MOUNT_POINT}` $${STYX_PORT}

  sshfs-ob2:
    build:
      context: .
      dockerfile: Dockerfile.sshfs
    image: metacoma/inferno-os-sshfs:latest
    privileged: true
    expose:
      - 1800
    cap_add:
      - SYS_ADMIN
    networks:
      - minetest-poc
    volumes:
      - ~/.ssh:/root/.ssh
      - ./files/inferno/:/usr/inferno/host:ro
    environment:
      - MOUNT_POINT=/usr/inferno/ob2
      - SSH_HOST=ob2
      - STYX_PORT=1800
    entrypoint:
      - sh 
      - -exc
      - |
        chown -R root:root /root/.ssh
        test -d $${MOUNT_POINT} || mkdir $${MOUNT_POINT}
        sshfs $${SSH_HOST}:/ $${MOUNT_POINT}
        emu /dis/sh /host/export.sh /`basename $${MOUNT_POINT}` $${STYX_PORT}
      
  jsonfs: 
    build:
      context: 9p/jsonfs
    image: metacoma/9p-jsonfs:latest
    networks:
      - minetest-poc
    volumes:
      - ./files/json/example.json:/tmp/json
    entrypoint: 
      - sh 
      - -c
      - |
        ./jsonfs -D -v -a :5640 /tmp/json

networks:
  minetest-poc:
