FROM i386/ubuntu:bionic
COPY inferno-os /usr/inferno/
ENV PATH=$PATH:/usr/inferno/Linux/386/bin
WORKDIR /usr/inferno
RUN apt-get update && \
    apt-get install -y build-essential libx11-dev libxext-dev libx11-6 libxext-dev \
    python3-pip libfuse2 curl git
RUN \
  MKFLAGS='SYSHOST=Linux OBJTYPE=386 ROOT='$PWD; \
  mk $MKFLAGS mkdirs && \
  mk $MKFLAGS emuinstall && \
  mk $MKFLAGS emunuke

RUN pip3 install git+https://github.com/opencredo/kubefuse.git
RUN curl -Lo /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
RUN chmod +x /usr/local/bin/kubectl

# Only for aws
#RUN curl -o /usr/local/bin/aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.7/2020-07-08/bin/linux/amd64/aws-iam-authenticator
#RUN chmod +x /usr/local/bin/aws-iam-authenticator
RUN pip3 install awscli


ENTRYPOINT ["emu"]
